config/routes.rb
Rails.application.routes.draw do

  root 'pages#new'

  resources :pages
  resources :books, only: [:create]

end

app/models/book.rb
class Book < ActiveRecord::Base

  belongs_to :content_page, class_name: "Page"
  has_many :chapter_pages, -> { order :id }, class_name: "Page"

  validates :content_page, presence: true
  before_save :fetch_title

  def doc
    @doc ||= Nokogiri::HTML::Document.parse "<html><body></body></html>"
  end

  def dir_name
    "book_#{title.parameterize}"
  end

  def generate
    self.title = content_page.title
    self.generate_chapters
    self.generate_content
  end

  def generate_chapters
    Dir.mkdir dir_name unless File.exists? dir_name

    content_page.links.each.with_index do |link,i|
      next if File.exists? "#{dir_name}/chapter_#{i+1}.html"
      puts "Generating chapter #{i+1}"
      page = Page.create book: self, url: link
      page.save_page "#{dir_name}/chapter_#{i+1}.html"
    end
  end

  def generate_content
    @doc = Nokogiri::HTML::Document.parse "<html><body></body></html>"

    body = doc.at_css "body"

    h1 = Nokogiri::XML::Node.new "h1", doc
    h1.content =  content_page.title

    body.add_child h1

    h2 = Nokogiri::XML::Node.new "h2", doc
    h2.content =  "Table of Contents"

    h1.add_next_sibling h2

    p = Nokogiri::XML::Node.new "p", doc
    p['style'] = "text-indent:0pt"

    h2.add_next_sibling p

    chapter_pages.each_with_index do |page, i|
      a = Nokogiri::XML::Node.new "a", doc
      a['href'] = page.filename || "#{dir_name}/chapter_#{i+1}.html"
      a.content = page.title #"Chapter #{i+1}: #{page.title}"
      p.add_child a
      br = Nokogiri::XML::Node.new "br", doc
      p.add_child br
      p.add_child "\n"
    end

    File.open('content.html', 'w') do |file|
      file.write doc.to_html
    end
  end

  private

  def fetch_title
    self.title = content_page.title
  end
end

app/models/page.rb
require 'open-uri'

class Page < ActiveRecord::Base
  before_validation :fetch_title, :fetch_links, :fetch_content
  attr_accessor :filename, :javascript

  belongs_to :book

  CONTENT_TAGS = ['#con_L', '#content', '#main', 'article', '.post-body', '.entry-content', '#chapterContent', '.yd_text2']
  REMOVE_TAGS = ['a', 'script', 'aside','footer', 'header', 'img', '.toplink', '.adsbygoogle']
  REMOVE_KEYWORDS = ['adsbygoogle', 'Share this:', 'Like this:']
  INSPECT_TAGS = ['tbody','div','table']
  def browser
    @@browser ||= Watir::Browser.new :chrome
  end

  def doc
    return @doc if @doc
    if javascript
      browser.goto url
      @doc ||= Nokogiri::HTML.parse(browser.html)
    else
      @doc ||= Nokogiri::HTML.parse(open(url))
    end
  end

  def fetch_title
    self.title ||= Pismo::Document.new(doc.to_html).title
  end

  def fetch_links
    return if self.links.present?
    self.links = doc.css('a').map{|link| link['href']}
    self.links = links.compact.select{|link| !link.include? 'javascript'}
    self.links = links.compact.map{|link| link.include?('http') ? link : /(.*\/).*$/.match(url)[1] + link }
  end

  def fetch_content
    html = ''
    CONTENT_TAGS.each do |css|
      candidate = doc.css(css)
      html = [html, candidate].select(&:present?).sort_by{|el| el.try(:to_html).length}.first
    end
    return if !html.present?
    REMOVE_TAGS.each do |css|
      html.css(css).each do |node|
        node.remove
      end
    end
    return if !html.present?
    REMOVE_KEYWORDS.each do |keyword|
      INSPECT_TAGS.each do |tag|
        html.css(tag).each do |node|
          node.remove if node.to_html.include? keyword
        end
      end
    end
    html = Sanitize.document(html.to_html, Sanitize::Config::RELAXED)
    self.content = html
  end

  def save_page path="page.html"
    self.filename = path
    File.open(path, 'w') do |file|
      file.write self.content
    end
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    page = Page.find(params[:page_id])
    book = Book.create(content_page: page)
    book.generate
    redirect_to page_path(page)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @content ||= Content.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def new
    @page = Page.new
  end

  def create
    @page = Page.create page_params
    render 'pages/show'
  end

  def show
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.update_attributes page_params
    links =  params[:page][:links].select{ |link| link.present? }

    @page.update_attributes links: links if links
    render 'pages/show'
  end

  private

  def page_params
    params.require(:page).permit(:url, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
1. Enter url below:

<%= form_for @content do |f| %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebToEbook</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/new.html.erb
1. Enter url below:

<%= form_for @page do |f| %>
  <%= f.text_field :url, class: 'form-control' %>
  <%= f.submit 'Fetch contents', class: 'btn btn-primary' %>
<% end %>

app/views/pages/show.html.erb
Found at <em><%= @page.url %></em>:


<%= form_for @page do |f| %>
  <%= f.submit :update, class: 'btn btn-primary' %>

  <%= link_to 'Generate book', books_path(page_id: @page.id), method: :post, class: 'btn btn-danger' %>

  <br/>
  <label>Title</label><br/>
  <%= f.text_field :title, value: @page.title %><br/>

  <label>Links</label><br/>
  <%= f.select :links, @page.links, {}, { multiple: true, size: @page.links.length } %>


<% end %>